go-kivik/kivik

- driver/couchdb/auth.go
- driver/couchdb/couchdb.go
- driver/couchdb/http.go
- driver/pouchdb/auth.go
- driver/pouchdb/pouchdb.go
> Move PouchDB auth to Authenticator interface

- cmd/kivik/main.go
- doc/COMPATIBILITY.md
- driver/pouchdb/bindings/pouchdb.go
- driver/pouchdb/pouchdb.go
- driver/proxy/proxy.go
- errors.go
- kivik.go
- logger/file/file.go
- logger/file/file_test.go
- logger/memory/memory.go
- logger/memory/memory_test.go
- serve/log.go
- serve/logger.go
- serve/params.go
- serve/serve.go
- test/createdb.go
- test/destroydb.go
- test/log.go
- test/server_test.go
- travis/install.sh
This does more test fixing, and adds the ability to serve logs. (should be two PRs, but meh...)
> Tests and logs

- db.go
- driver/couchdb/chttp/chttp.go
- driver/couchdb/couchdb.go
- driver/couchdb/db.go
- driver/couchdb/options.go
- driver/driver.go
- driver/fs/db.go
- driver/fs/fs.go
- driver/memory/db.go
- driver/memory/memory.go
- driver/pouchdb/db.go
- driver/pouchdb/pouchdb.go
- kivik.go
And use this to force commits, instead of my previous AutoFlush hack.
> Add support for db-specific options

- driver/couchdb/bulk.go
- driver/couchdb/chttp/auth.go
- driver/couchdb/chttp/chttp.go
- driver/couchdb/chttp/chttp_test.go
- driver/couchdb/config.go
- driver/couchdb/db.go
For greater efficiency on large requests.
> Stream JSON encoding to HTTP requests

- driver/couchdb/auth.go
Awesome library, but it seems that you've missed something :)
> Fixed CouchDB authentication interface

- config.go
- doc/COMPATIBILITY.md
- test/kt/kt.go
But don't remove it yet--the server still needs to read config, and until I
have time to make it read YAML or something else, I'll leave it around just
for that.
> Document that the Config() method is going away.

- driver/couchdb/bulk.go
- driver/couchdb/chttp/chttp.go
- driver/couchdb/chttp/chttp_test.go
- driver/couchdb/db.go
> Attempt to solve a race condition

- bulk.go
- changes.go
- db.go
- driver/changes.go
- driver/couchdb/changes.go
- driver/couchdb/db.go
- driver/driver.go
- driver/fs/db.go
- driver/iterator.go
- driver/memory/db.go
- driver/pouchdb/changes.go
- driver/proxy/proxy.go
- driver/rows.go
- driver/rows_test.go
- find.go
- iterator.go
- iterator_test.go
- rows.go
- test/client/config.go
- updates.go
> Use a common Iterator for all package iterators

- authdb/authgroup/authgroup_test.go
- authdb/confadmin/confadmin_test.go
- authdb/couchauth/couchauth_test.go
- authdb/usersdb/usersdb_test.go
- driver/fs/db.go
- driver/memory/db.go
- test/client/config.go
- test/fs.go
- test/memory.go
- test/test.go
- Switch to random user names for user tests
- Clean up test users during test startup
Fixes #103
> User test improvements

- db.go
- driver/couchdb/db.go
- driver/couchdb/db_test.go
- driver/driver.go
- driver/fs/db.go
- driver/memory/db.go
- driver/pouchdb/db.go
- driver/proxy/proxy.go
- test/client/version.go
- test/cloudant.go
- test/couchdb16.go
- test/couchdb20.go
- test/db/stats.go
- test/fs.go
- test/memory.go
- test/pouchdb.go
- test/server.go
> Rename DBInfo() to Stats() to be more specific.

- attachments.go
- db.go
- driver/couchdb/attachments.go
- driver/driver.go
- driver/fs/db.go
- driver/memory/db.go
- driver/pouchdb/attachments.go
- driver/proxy/proxy.go
Fixes #91 by renaming it to something that I think makes more sense.
> Rename Checksum to MD5sum to be more descriptive.

- README.md
- doc.go
- driver/doc.go
> Update package documentation.

- errors.go
- errors_test.go
> Document kivik errors

- updates.go
> Clean up DBUpdates interface a bit

- test/test.go
> Clean up stale replications during tests

- README.md
Signed-off-by: Hui Kang <kangh@us.ibm.com>
> README: fixing the missing import context in the example

- replication.go
- replication_test.go
> Handle nil replications gracefully

- driver/pouchdb/replication.go
- driver/pouchdb/replicationEvents.go
Works around https://github.com/pouchdb/pouchdb/issues/6655
> Work around inconsistent timestamp types from PouchDB

- bulk_test.go
- db_test.go
- driver/couchdb/chttp/chttp_test.go
- driver/couchdb/db_test.go
- driver/memory/alldocs_test.go
- driver/memory/db_test.go
- driver/memory/find_test.go
- driver/memory/memory_test.go
- driver/memory/security_test.go
- driver/memory/store_test.go
- driver/pouchdb/find_test.go
- driver/rows_test.go
- glide.yaml
- iterator_test.go
- serve/couchserver/alldbs_test.go
- serve/couchserver/db_test.go
- serve/couchserver/errors_test.go
- serve/couchserver/root_test.go
- serve/couchserver/session_test.go
- serve/logger/logger_test.go
- test/client/alldbs.go
- test/client/getreplications.go
- test/db/alldocs.go
- test/db/bulk.go
- test/db/find.go
- test/db/get.go
- test/db/getindexes.go
- test/db/query.go
- test/db/security.go
> Update for newer diff version

- glide.yaml
- serve/couchserver/context.go
- serve/couchserver/context_test.go
- serve/couchserver/couchserver.go
- serve/routes.go
Use chi's Encoding middleware. Fixes #203
> use chi's compression middleware

- glide.yaml
- serve/routes.go
> Switch from alice to chi middleware handler

- .travis.yml
- README.md
- constants.go
- doc/COMPATIBILITY.md
- driver/couchdb/chttp/chttp_test.go
- driver/driver.go
- proxy/proxy_test.go
- test/couchdb_test.go
- travis/install.sh
- travis/test.sh
> Add support for CouchDB 2.1.x

- authdb/authgroup/authgroup.go
- authdb/authgroup/authgroup_test.go
- authdb/confadmin/confadmin.go
- authdb/confadmin/confadmin_test.go
- authdb/couchauth/couchauth_test.go
- authdb/usersdb/usersdb.go
- authdb/usersdb/usersdb_test.go
- db.go
- driver/couchdb/chttp/errors_test.go
- driver/couchdb/client.go
- driver/couchdb/replication.go
- driver/pouchdb/bindings/nofind_test.go
- driver/pouchdb/db_test.go
- driver/pouchdb/pouchdb.go
- errors/errors.go
- errors/errors_test.go
I'll eventually remove errors.StatusCode, as my goal is for it to be a non-public package.
> Switch from errors.StatusCode to kivik.StatusCode

- .travis.yml
- travis/install.sh
- travis/test.sh
> Run tests against Couch 1.7

- travis/install.sh
> Run tests against 2.1.1 instead of 2.0.0

- constants.go
- errors/errors.go
- errors/status.go
- errors/status_test.go
Relates to https://github.com/go-kivik/pouchdb/issues/19
> Custom StatusText() implementation

- .travis.yml
- ISSUE_TEMPLATE.md
- README.md
> Drop Go 1.7 support

- constants.go
> Remove StatusBadContentType and StatusResourceNotAllowed constants

- driver/driver.go
- find.go
- find_test.go
- mock_test.go
> Merge Explainer interface into the Finder interface.

- db.go
- db_test.go
> Defer Get() errors until row.ScanDoc()

- kivik.go
- kivik_test.go
> Change CreateDB() to return a valid DB value.

- attachments.go
- attachments_test.go
- db.go
- db_test.go
- driver/driver.go
- mock/db.go
> Major Attachments overhaul

- attachments.go
- attachments_test.go
- db.go
- db_test.go
- driver/driver.go
- driver/rows.go
- mock/attachments.go
> Streaming attachments support

- README.md
> Update README to mention Cayley as a consumer of Kivik

- db.go
- db_test.go
- driver/driver.go
> Add cluster config and raw response fields to the database stats query

- db.go
- driver/driver.go
- kivik.go
- kivik_test.go
- mock/client.go
> Add support for multiple db stats fetches

- driver/rows.go
- rows.go
- rows_test.go
...to accommodate 'not found' rows from some queries
> Extend driver.Row with Error field 

- db.go
- db_test.go
- driver/driver.go
- mock/db.go
> Add Purge support

- driver/driver.go
- kivik.go
- kivik_test.go
- mock/client.go
> Add Ping support

- .travis.yml
(Except for GopherJS which isn't quite ready yet)
> Bump version to Go 1.12

- constants.go
- rows.go
> A couple of documentation fixes

- find.go
> Fix link to CouchDB index documentation

- README.md
> Update installation instructions for stable branch

- changes.go
- changes_test.go
- driver/changes.go
- mock/changes.go
- rows.go
> Extend Changes functionality to support normal feeds.

- README.md
and to refer to the stable docs for stable installation.
Related to https://github.com/go-kivik/kivik/issues/372
> Update README to show documentation for the devel branch

- changes.go
- changes_test.go
- driver/changes.go
- mock/changes.go
Fixes https://github.com/go-kivik/kivik/issues/383
> Add Changes ETag support

- cluster.go
- db.go
- db_test.go
- errors.go
- errors_test.go
- find.go
- iterator.go
- kivik.go
- replication.go
- rows.go
- session.go
- updates.go
- xerrors_13.go
- xerrors_pre13.go
> Update errors to conform to Go 1.13 error standards

- config.go
- config_test.go
- driver/config.go
- mock/client.go
> Add experimental configuration support

- db.go
- db_test.go
- driver/driver.go
- mock/db.go
- testdata/TestRevsDiff_success
This is the last method needed to implement client-driven replication
> Add _revs_diff support

- db.go
- db_test.go
- driver/partition.go
- internal/mock/db.go
- testdata/TestPartitionStats_success
> Add support for PartitionStats method

- README.md
client.DB does not return an error anymore
> Fix readme for v3

- README.md
> client.DB does not return an error anymore

- driver/rows.go
- internal/mock/rows.go
- rows.go
- rows_test.go
> Add QueryIndex() support to Rows for multi-query support

- doc.go
- errors_example_test.go
Relates to #488 
Obsoletes https://github.com/go-kivik/kivik/wiki#error-handling
> Update error handling info from the wiki

- db_example_test.go
- doc.go
- errors_example_test.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- iterator_test.go
- kivik.go
- kivik_example_test.go
- kivik_test.go
- registry.go
Move all useful info from the wiki into the godoc.
> Godoc updates

- .gitlab-ci.yml
- .golangci.toml
- bulk_test.go
- cluster.go
- cluster_test.go
- db.go
- db_test.go
- driver/driver.go
- errors.go
- internal/mock/client.go
> Add support for the /_membership endpoint

- driver/driver.go
- errors_example_test.go
- internal/mock/client.go
- iterator_test.go
- kivik.go
- kivik_example_test.go
- kivik_test.go
> Drop ctx argument for DB() method

- errors.go
- errors_test.go
> Frop FromServer field from error type

- .gitlab-ci.yml
- constants.go
- db.go
- db_test.go
> Allow passing rev to Delete() function via options

- db.go
- db_test.go
> Allow rev in options for DeleteAttachment()

- db.go
- db_test.go
> Allow providing rev via options for PutAttachment method

- .gitlab-ci.yml
- Drop Go 1.11 & 1.12
- Add  Go 1.17 - 1.20
> Update Go versions

- driver/rows.go
- resultset.go
- resultset_test.go
> Drop non-io.Reader Doc and Value fields from driver.Row

- iterator.go
- resultset.go
- resultset_test.go
> Fix single-item mode for empty result sets

- README.md
- db.go
- db_test.go
- driver/driver.go
- internal/mock/client.go
- internal/mock/db.go
- kivik.go
- kivik_test.go
> Remove context argument to Close() methods

- db.go
- db_test.go
> Don't try to assing rev to nil map

- couchdb/changes.go
- couchdb/changes_test.go
> Use POST for changes feed to support large lists of doc_ids

- couchdb/db.go
- db.go
- db_test.go
- driver/driver.go
- internal/mock/db.go
- mockdb/gen/main.go
- pouchdb/db.go
> Merge driver.DBCloser into driver.DB interface

- constants.go
- couchdb/couchdb.go
- kiviktest/client/version.go
> Remove unused vendor constants

- couchdb/bulkget.go
- couchdb/bulkget_test.go
> Unexport couchdb.BulkGetError type

- options.go
- options_test.go
> Add Duration() function to ease handling of duration-based query parameters

- driver/driver.go
- security.go
> Add optional fields for Cloudant _security documents

- driver/driver.go
> Clarify use of some Replication methods

- couchdb/attachments_test.go
- couchdb/db_live_test.go
- couchdb/db_test.go
- couchdb/replication.go
- couchdb/scheduler.go
- couchdb/test/couchdb22.go
- couchdb/test/couchdb23.go
- couchdb/test/couchdb30.go
- couchdb/test/couchdb31.go
- couchdb/test/couchdb32.go
- couchdb/test/couchdb33.go
- db_example_test.go
- db_test.go
- kiviktest/db/alldocs.go
- kiviktest/db/query.go
- mockdb/db_test.go
- options.go
- pouchdb/test/test.go
> Unexport the params type, and add a Params() function

- couchdb/db.go
- couchdb/db_test.go
> Use io.Seeker method to determine attachment size when possible

- db.go
> Complete plumbing of the Cloudant-specific security fields

- attachments_test.go
- cmd/kivik/cmd/test_test.go
- cmd/kivik/config/log_test.go
- couchdb/auth_test.go
- couchdb/bulkget_test.go
- couchdb/changes_test.go
- couchdb/chttp/chttp_test.go
- couchdb/db_live_test.go
- couchdb/db_test.go
- internal/registry/registry_test.go
- pouchdb/changes_test.go
- pouchdb/db_test.go
- x/fsdb/changes_test.go
- x/fsdb/get_test.go
- x/fsdb/revsdiff_test.go
- x/fsdb/security_test.go
- x/fsdb/test/fs_test.go
Attempt at #751 , but didn't work. Still a useful change.
> Use t.Cleanup in place of a defer

- replicate.go
- replicate_test.go
> Convert replication callback to a functional option

- cmd/kivik/cmd/root_test.go
> Allow rc in Go version for tests

- cmd/kivik/cmd/replicate.go
- replicate.go
- replicate_live_test.go
- replicate_test.go
> Convert copySecurity to functional option

- rows_test.go
> Add tests for single call to Attachments

- go.mod
- go.sum
- x/fsdb/cdb/decode/yaml.go
- x/fsdb/testdata/TestGet_atts_split_between_two_revs
- x/fsdb/testdata/TestGet_no_winner,_tied_rev
- x/fsdb/testdata/get_nowinner/.foo/1-yyy.yaml
- x/fsdb/testdata/get_split_atts/.foo/1-yyy.yaml
> Replace yaml.v2 with yaml.v3

- cmd/kivik/output/output_test.go
- cmd/kivik/output/util.go
> Don't kick off json.Marshal goroutine until first Read call

- cmd/kivik/main.go
> cmd/kivik: Catch SIGINT/SIGTERM, and trigger shutdown

- db.go
- errors.go
- resultset.go
> Return an error from Attachments() when there are no attachments

- driver/driver.go
Applies suggestion in https://github.com/go-kivik/kivik/issues/716#issuecomment-1724513190
> Apply fix to security document marshaling

- README.md
> Update README to say 4.x is stable

- x/sqlite/README.md
- x/sqlite/collation.go
- x/sqlite/collation_test.go
- x/sqlite/go.mod
- x/sqlite/query.go
- x/sqlite/query_test.go
- x/sqlite/schema.go
- x/sqlite/sqlite.go
- x/sqlite/views.go
Requires newer version of sqlite driver
> Add collation support

- couchdb/client.go
- couchdb/client_test.go
> Fix bug 929

- x/sqlite/designdocs_test.go
- x/sqlite/localdocs_test.go
- x/sqlite/options.go
- x/sqlite/query.go
- x/sqlite/schema.go
- x/sqlite/views.go
- x/sqlite/views_test.go
And at the same time, return the keys in the proper format
> Support proper collation for default views

- couchdb/db_test.go
- db_example_test.go
And add tests to confirm
Closes #975, which was actually solved long ago. Just the example wasn't properly updated.
> Update example to show current behavior of key handling

- driver/driver.go
- find.go
- find_test.go
- mockdb/db_test.go
And part of #1015 , which can be done without breaking backward compatibility.
> Merge Find() options into query

- .gitlab-ci.yml
- pouchdb/find_test.go
- pouchdb/indexeddb/purge_test.go
- pouchdb/internal/pouchver.go
- pouchdb/pouchdb9-package.json
- pouchdb/test/test.go
> Add PouchDB 9 to test matrix

- couchdb/client.go
- couchdb/client_test.go
- couchdb/test/session.go
> Fix nil map assignment panic
