.travis.yml, cmd/kivik/main.go, driver/couchdb/http.go, test/test.go, travis/install.sh, travis/test.sh
Go 1.8 changed the `testing` package's API. This was a known risk.... but this PR makes it so that I no longer depend on that API.  The down side is that now the 'kivik test' command doesn't have the same style output as 'go test', but this can be addressed manually if I ever actually care.
=> Redo tests a bit

cmd/kivik/main.go, test/alldbs.go, test/createdb.go, test/db_alldocs.go, test/db_put.go, test/dbexists.go, test/destroydb.go, test/go17testing.go, test/go18testing.go, test/go19testing.go, test/gopherjs_test.go, test/info.go, test/log.go, test/membership.go, test/nonjs_test.go, test/server_test.go, test/test.go, test/test_test.go, test/testing.go, test/uuids.go
Several changes related to testing:
- Use the `testing` package again, and make it work with Go 1.7, 1.8, and 1.9
- Use `t.Parallel()` where possible.
- Add a test cleanup mode to the command line tool.
- Run tests for unauthenticated users now, too.
- Test CreateDB() for when the db already exists.
And other misc changes.
=> Rework testing

driver/couchdb/attachments.go, driver/couchdb/chttp/chttp.go, driver/couchdb/chttp/encode.go, driver/couchdb/chttp/encode_test.go, driver/couchdb/db.go, driver/couchdb/db_test.go, test/db/put.go
This is intended as a more complete solution to #60
=> Properly encode a wider range of special characters in Document IDs

driver/couchdb/chttp/chttp.go, test/client/config.go, test/kt/kt.go
I believe this race is the result of re-using the http request in retries.
=> Attempt to solve data race in http library

db.go, driver/couchdb/db.go, driver/driver.go, serve/flush.go, test/cloudant.go, test/couchdb20.go, test/db/flush.go
CouchDB 2.0 no longer supports this, and it seems rather worthless anyway,
so just get rid of it.
Fixes #87
=> Ignore timestamps from Flush()

authdb/confadmin/confadmin_test.go, authdb/couchauth/couchauth_test.go, authdb/usersdb/usersdb.go, db.go, driver/couchdb/db.go, driver/driver.go, driver/fs/db.go, driver/memory/db.go, driver/pouchdb/db.go, driver/proxy/proxy.go, test/db/copy.go, test/db/delattachment.go, test/db/get.go, test/db/rev.go, test/kt/kt.go
This copies sql's behavior, but most important, it means Get() doesn't
accept both input _and_ output parameters.
Fixes #86
=> Switch single-document Get() to return a Row

test/db/putattachment.go
... so we don't try to re-use an io.Reader
Fixes #110
=> Move attachment instantiation inside retry loop

driver/pouchdb/bindings/errors.go, driver/pouchdb/bindings/errors_test.go, driver/pouchdb/bindings/errors_test.inc.js, driver/pouchdb/replication.go, driver/pouchdb/replicationEvents.go, package.json, test/client/replicate.go, test/cloudant.go, test/couchdb16.go, test/couchdb20.go, test/pouchdb.go
I discovered in the course of working on #134 that some NodeJS system errors were improperly handled by the PouchDB driver. This fixes the known cases.
=> Fix handling of certain NodeJS errors

driver/memory/memory.go, driver/memory/memory_test.go, kivik.go
The list of allowed system databases is backend-specific (e.g. CouchDB 2.0 allows `_global_changes`, while 1.6 does not), so this check belongs in the backend or per-driver, rather than in the main Kivik library.
=> Move system db check into the individual driver.

authdb/authgroup/authgroup_js_test.go, authdb/authgroup/authgroup_test.inc.js, driver/couchdb/chttp/chttp_js_test.go, driver/couchdb/chttp/chttp_test.inc.js, driver/couchdb/main_js_test.go, driver/couchdb/main_test.inc.js
GopherJS improperly includes `*_test.inc.js` files when building non tests.  See https://github.com/gopherjs/gopherjs/issues/655
This works around the bug so that failure loading the `xhr2` module doesn't cause a crash in the browser.
=> Wrap xhr2 loading in try/catch block to work around GopherJS limitation

driver/pouchdb/bindings/nofind_test.go, driver/pouchdb/db_test.go, test/pouchdb_test.go
defaults() returns a new constructor, rather than modifying the existing
one.  This fixes the previous faulty assumption.
=> Fix memdown usage during tests

driver/memory/db.go, driver/memory/db_test.go
Long-term, attachments need to be stored properly, but as attachments, not
in the document directly.
=> Remove _attachments key when storing docs in memory driver

collate/collate.go, collate/collate_test.go, collate/raw.go, collate/raw_test.go
This library isn't being used yet, but will be used by the #166.  Long-term, this should be expanded to support CouchDB's ICU collation method, but it's a bit magical, and [it looks like PouchDB](https://github.com/pouchdb/pouchdb/issues/40) decided not to even try to mimic that behavior, so maybe it can be considered low-priority.
=> Add basic library with raw collation support.

.travis.yml
It wasn't working. From the Travis log:
```
adding /home/travis/gopath/src/github.com/flimzy/kivik/node_modules to cache
creating directory /home/travis/gopath/src/github.com/flimzy/kivik/node_modules
adding /home/travis/gopath/pkg to cache
creating directory /home/travis/gopath/pkg
adding /var/lib/docker to cache
docker is not yet cached
/var/lib/docker: Permission denied
```
=> Don't try to cache docker dir

bulk.go, bulk_test.go, driver/driver.go, kivik.go
This PR adds an optional `options` parameter to the `BulkDocs()` method, to allow setting options such as `new_edits`, the `X-Couch-Full-Commit` header, or `all_or_nothing` (for versions < 2.0).
Fixes #208 .
This PR aims for near 100%-backward compatibility.  Client code should remain 100% backward compatible, as the new argument is optional.  The old function signature was:
BulkDocs(ctx context.Context, docs []interface{}) (*BulkResults, error)
Whereas the new signature is:
BulkDocs(ctx context.Context, docs []interface{}, options ...Options) (*BulkResults, error)
The only breaking change is that the definition of `driver.BulkDocer` changed.  The old definition lives on for now, as `OldBulkDocer`, but any reference to the exported `driver.BulkDocer` symbol will likely break. As the only …
=> Allow passing options to the BulkDocs() method

db.go, db_test.go, driver/driver.go, mock_test.go
These accept If-None-Match, which has no way of being passed without this.
=> Allow passing options to a couple more methods

attachments.go, attachments_test.go
With this, it should be possible to embed `kivik.Attachment` and `kivik.Attachments` fields in documents for use by `Put` and `Get`. Example:
```
doc := map[string]interface{}{
// .. other fields
"_attachments": kivik.Attachments{
"foo.txt": &kivik.Attachment{
ReadCloser: ioutil.NopCloser(strings.NewReader("test content"),
ContentType: "text/plain",
},
},
}
```
Fixes #95.
=> Add better support for Attachments

auth/auth.go, auth/basic/basic.go, auth/cookie/cookie.go, authdb/authdb.go, authdb/authgroup/authgroup.go, authdb/confadmin/confadmin.go, authdb/couchauth/couchauth.go, authdb/usersdb/usersdb.go, collate/collate.go, doc.go, driver/common/common.go, driver/couchdb/chttp/chttp.go, driver/couchdb/couchdb.go, driver/doc.go, driver/memory/memory.go, driver/pouchdb/bindings/pouchdb.go, driver/pouchdb/bindings/poucherr/poucherr.go, driver/pouchdb/pouchdb.go, driver/util/doc.go, errors/errors.go, proxy/proxy.go, test/conf.go
in preparation for package rename at v2.0
Relates to #178
=> Pin import paths to github.com/flimzy/kivik

db.go, db_test.go, driver/bulkget.go, mock/db.go
Alternative to #340. See also https://github.com/go-kivik/couchdb/pull/139
The purpose of this PR is to explore whether adding BulkGet support can be done without extending the [`Rows`](https://godoc.org/github.com/go-kivik/kivik#Rows) interface. I believe I have a working solution, but some work is still needed on the CouchDB driver.
=> Add BulkGet support

db.go, db_test.go, driver/bulkget.go
directly access 'driver' package.
=> Add BulkDocReference type to kivik package, so consumers don't need to

bulk.go, changes.go, cluster.go, db.go, db_test.go, glide.gopherjs.yaml, kivik.go, kivik_test.go, replication.go
To facilitate shorter code, this PR defers errors from the `DB()` and `CreateDB()` calls.  Example usage:
```
db, err := client.DB( ... )
if err != nil {
return err
}
if _ err = db.Put( ... ); err != nil {
return err
}
```
Can now be shortened to:
```
db := client.DB( ... )
if _ err = db.Put( ... ); err != nil {
return err
}
```
or chained:
```
if err := client.DB( ... ).Put( ... ); err != nil {
return err
}
```
This also simplifies some internal logic, eliminating the need for the `imdario/mergo` dependency.
=> Defer DB() and CreateDB() errors

db.go, db_test.go, driver/driver.go, kivik.go, kivik_test.go, mock/client.go, mock/db.go
DB.Close() is used by PouchDB.
Client.Close() will likely be used by FS driver and mock driver.
=> Add Client.Close() and DB.Close() options

db.go, db_test.go, iterator.go, iterator_test.go
"BadGateway" suggests an invalid response from the server, but this isn't
known.  The data type could be to "blame", so best not to add any
assumptions.
=> Pass JSON unmarshaling errors through unaltered

changes.go, changes_test.go
=> Fix panics when attempting to access uninitialized changes metadata

changes.go, db.go, db_test.go, iterator.go, iterator_test.go, rows.go
Instead of special casing *[]byte and *json.RawMessage, and some silly
cusotm error messages, why not simplify and use the standard marshaler?
This is, of course, a breaking change, so not eligible for v3.
=> Simplify JSON unmarshaling

driver/rows.go, rows.go, rows_test.go
This won't make much difference for normal CouchDB usage, where each JSON
segment must be parsed in turn.
The immediate reason for this is to allow consolidating the Row and Rows
type for the purpose of https://github.com/go-kivik/kivik/issues/398
This makes it unnecessary to load document into memory, in the case of a simple
single-document Get(), once these types are consolidated.
This may also allow optimizations for other backends in the future, to not
load an entire document into memory before needed.
=> Allow use of io.Readers for Doc and Value in iterators

bulk_test.go, db.go, db_test.go
Simplify the handling of various types of doc input, to reduce the unmarshal/re-marshal cycles.  Also, drops support for `[]byte` documents--use a `json.RawMessage` instead.
=> Reduce marshal/remarshal cycles

.gitlab-ci.yml, db.go, db_test.go
Same as #518, but for DeleteAttachment()
=> Allow rev in options for DeleteAttachment()

db.go, db_test.go
for consistency with the general `Put()`
=> Eliminate 'rev' argument to PutAttachment func

db.go, db_example_test.go, db_test.go, find.go, find_test.go, iterator_test.go, rows.go
Relates to #398.
As a step toward unifying `*Rows` with `*Row`, this PR modifies all methods that return a `*Rows` value (i.e. `Query()`, `AllDocs()`, `Find()`, etc), to forward the error to the first call to `ScanDoc()` or related.
=> Forward errors from any methods that return a *Rows object

db.go, iterator.go, row.go, rows.go, rows_test.go
- Add a new `*row` type (still unused) that wraps `*Row`, but satifies the `Rows` interface
- Tweaked behavior of `Rows` methods to work on the last item in the iterator, even after close.
=> Work toward integrating *Row into Rows

find.go
The previous [link](https://docs.couchdb.org/en/2.0.0/api/database/find.html#db-find) leads to the page with 404 error.
=> Fix `Find` documentation (link to CouchDB)

bulk.go, changes.go, iterator.go, rows.go, updates.go
And remove duplicate Next/Err/Close methods, relying on the promoted ones instead.
=> Move EOQ() method from *iter to *Rows, so it's not promoted on all iterators

attachments.go, bulk.go, bulk_test.go, changes.go, changes_test.go, cluster.go, cluster_test.go, config.go, config_test.go, db.go, db_test.go, errors.go, find.go, find_test.go, internal/mock/bulkresults.go, internal/mock/changes.go, internal/mock/dbupdates.go, iterator.go, iterator_test.go, kivik.go, kivik_test.go, replication.go, replication_test.go, resultset.go, resultset_test.go, session.go, session_test.go, updates.go, updates_test.go
- Make Close() block until all subordinate DB operations complete
- Make all other calls fail once Close() is called
Relates to #611
=> Change client.Close() semantics a bit

db.go, db_test.go, driver/driver.go, internal/mock/db.go, kivik_test.go
=> Pass rev as options to driver instances

db.go, db_test.go, driver/driver.go, internal/mock/db.go, pouchdb/db.go
=> Make Security/SetSecurity optional for a backend

couchdb/chttp/errors.go, couchdb/mock_test.go, errors.go
It was made obsolete with the advent of Go 1.13.  I think we can stop supporting it now.
=> Remove legacy support for the github.com/pkg/errors.causer interface

README.md, couchdb/auth.go, couchdb/auth_test.go
=> Remove SetTransport auth method

couchdb/config.go, couchdb/config_test.go, couchdb/doc.go
=> Use empty string to indicate CouchDB 1.x config node

couchdb/chttp/chttp.go
- Composite values before `_rev` were parsed token-by-token, rather than discarding the entire value
- A value of `"_rev"` would have confused it
=> Fix 2 bugs in readRev:

couchdb/chttp/chttp.go, couchdb/constants.go, couchdb/db.go, couchdb/db_test.go
=> Add open_revs support

cmd/kivik/cmd/root_test.go
=> Normalize IPv4 & IPv6 error messages in tests

bulk_test.go, changes_test.go, cluster.go, cluster_test.go, config.go, config_test.go, db.go, db_test.go, errors.go, find.go, find_test.go, internal/errors.go, kivik_test.go, pouchdb/bindings/pouchdb.go, replication.go, replication_test.go, session_test.go, updates_test.go
=> Use constants in place of error variables

db.go, resultset.go, resultset_test.go
=> Remove the single-doc operating mode of the resultset

couchdb/client.go, couchdb/client_test.go, updates.go
=> Support normal mode & other parameters for DBUpdates

couchdb/client.go, couchdb/client_test.go, couchdb/rows.go, driver/updates.go, internal/mock/dbupdates.go, mockdb/updates.go, mockdb/updates_test.go, options.go, options_test.go, updates.go, updates_test.go
=> Add last_seq support for db updates

x/sqlite/reduce.go, x/sqlite/reduce/reduce.go, x/sqlite/reduce/reduce_test.go
Works so far. Needs to be wired up, to see how it actually works.
=> A re-implementation of reduce functionality, which should allow for proper caching of intermediate results

constants.go
To reflect new Go 1.23 iterator functions
Also adds PouchDB 9 to tests.
=> Bump version to 4.3.0

x/sqlite/changes.go, x/sqlite/changes_test.go, x/sqlite/js/js.go, x/sqlite/query.go, x/sqlite/query_test.go, x/sqlite/reduce/functions.go
For now, this is just to make it easy for _changes to re-use view functions, but eventually this will make it possible for other drivers (i.e. fsdb) to re-use these functions as well.
=> Move JS functions into a separate package

cmd/kivik/README.md, cmd/kivik/errors/errors.go, couchdb/chttp/chttp_test.go, couchdb/chttp/trace_test.go, driver/driver.go, driver/partition.go, int/mock/replication.go, iterator.go, mockdb/clientmock.go, pouchdb/bindings/pouchdb.go, replicate.go, x/fsdb/cdb/revid.go, x/fsdb/changes.go, x/mango/ast_test.go, x/server/auth.go, x/server/auth/auth.go, x/server/config/config.go, x/sqlite/options.go, x/sqlite/options_test.go
The PR corrects spelling mistakes in comments, test case names, and documentation files.
=> Fix typos in comments, tests, and docs

x/sqlite/schema.go, x/sqlite/sqlite.go, x/sqlite/sqlite_test.go
And fix dbname validation to allow specific system databases
=> x/sqlite: Improve DestroyDB to remove all tables

couchdb/client.go, couchdb/client_test.go, couchdb/mock_test.go
Currently, `url.PathEncode` is applied for `CreateDB` and `DestroyDB`, but not for `DBExists`, which behave inconsistently.
I discovered this when I created a database that included special characters, but `DBExists` would not correctly detect a database even after being created.
For a reproducible example, I could not find a good test case to update, as the request path is never part of the test assertion. You can reproduce the issue with the following setup:
**docker-compose.yml**
```yaml
services:
couchdb:
image: couchdb:3
ports:
- 5984:5984
environment:
COUCHDB_USER: admin
COUCHDB_PASSWORD: password
```
**go.mod**
```
module kivik-testing
go 1.23.0
require github.com/go-kivik/kivik/v4 v4.3.0
require (
github.com/google/uuid v1.6.0 // indirect
golang.org/x/net v0.17.0 // indirect …
```
=> fix(couchdb): use url.PathEscape in DBExists for consistency with other DB* methods

x/collate/collate.go, x/mango/match_test.go, x/mango/selector.go
This PR fixes the evaluation of `$exists: false` by making `fieldNode.Match()` always pass the value to the condition, even if it is not found in the map.
It also makes it possible to do subfield lookups using dot notation (e.g. `foo.bar.baz`) as mentioned in the [CouchDB documentation](https://docs.couchdb.org/en/stable/api/database/find.html#subfields).
This PR fixes https://github.com/go-kivik/kivik/issues/1043.
=> x/mango: Fix evaluation of `$exists: false` always failing
